Playitowl/Areas/Administration/Controllers/VideoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using Playitowl.Service;

namespace Playitowl.Areas.Administration.Controllers
{
    [Authorize(Roles ="AppAdmin")]
    public class VideoController : Controller
    {
        private IVideoService _videoService;
        private IPlaylistService _playlistService;


        public VideoController(IVideoService videoService, IPlaylistService plService)
        {
            _videoService = videoService;
            _playlistService = plService;
        }

        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        { 
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            var videos = _videoService.GetSorted(sortOrder);
            if (!String.IsNullOrEmpty(searchString))
            {
                videos = videos.Where(s => s.Name.Contains(searchString));
            } 
            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(videos.ToPagedList(pageNumber, pageSize));
             
        } 

        public ActionResult Delete(string id)
        {
            _videoService.Remove(id);
            return RedirectToAction("Index");
        }
    }
}

Playitowl/Areas/Main/Controllers/VideoController.cs
using System;
using System.Web.Mvc;
using Playitowl.Models; 
using Playitowl.Models.Vm;
using Playitowl.Service;

namespace Playitowl.Areas.Main.Controllers
{
    public class VideoController : Controller
    {
        private IVideoService _videoService;
        private IPlaylistService _playlistService;
         

        public VideoController(IVideoService videoService, IPlaylistService plService)
        {
            _videoService = videoService;
            _playlistService = plService;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <param name="url"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GetVideoInfoRes(String id, String url = null)
        {
            Video targetVideo = _videoService.Resolve(url ?? id);
            VideoVm model = AutoMapper.Mapper.Map<VideoVm>(targetVideo);
            return PartialView("TargetVideo", model);
        }
         

    }
}

Playitowl/Areas/Administration/Views/Video/Index.cshtml
@model PagedList.IPagedList<Playitowl.Models.Video>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Videos";
}

<h2>Videos</h2>

<p> 
</p>
@using (Html.BeginForm("Index", "Video", FormMethod.Get))
{
    <p>
        Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Id", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            Name
        </th>
        <th>
            @Html.ActionLink("Thumbnail", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Thumb)
            </td>
            <td> 
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))