Playitowl/Areas/Administration/Controllers/PlaylistController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using PagedList;
using Playitowl.Service;

namespace Playitowl.Areas.Administration.Controllers
{
    [Authorize(Roles = "AppAdmin")]
    public class PlaylistController : Controller
    {
        private IVideoService _videoService;
        private IPlaylistService _playlistService;


        public PlaylistController(IVideoService videoService, IPlaylistService plService)
        {
            _videoService = videoService;
            _playlistService = plService;
        }

        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            var playlists = _playlistService.GetSorted(sortOrder);
            if (!String.IsNullOrEmpty(searchString))
            {
                playlists = playlists.Where(s => s.Name.Contains(searchString));
            }
            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(playlists.ToPagedList(pageNumber, pageSize));

        }

        public ActionResult Delete(string id)
        {
            _playlistService.Remove(id);
            return RedirectToAction("Index");
        }
    }
}

Playitowl/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - PlayItOwl</title>
    <link rel="stylesheet" href="~/wwwroot/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Content/stylesheets/screen.css" />
    <link rel="stylesheet" href="~/Content/stylesheets/print.css" />
    <link rel="stylesheet" href="~/Content/stylesheets/ie.css" />

    @RenderSection("Styles", required: false)
    <script src="~/wwwroot/lib/modernizr/modernizr.js"></script>
    <script>
        (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date(); a = s.createElement(o),
            m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-70678266-1', 'auto');
        ga('send', 'pageview');

        window.fbAsyncInit = function () {
            FB.init({
                appId: '1541270902831007',
                xfbml: true,
                version: 'v2.5'
            });
        };
    </script>

</head>
<body>

    @Html.Partial("_navbar")

    <nav class="side main" style="display: none;">
        <ul class="menu sidebar-list">
            <!--<li>Format:</li>
            <li>Format:</li>
            <li>Auto-cut:</li>
            <li>Sync:</li>-->
            @RenderSection("sidebarItems", required: false)
        </ul>
    </nav>



    <div class="container body-content hardware-accelarate" data-state="neutral">
        <div class="body-wrap">
            @RenderBody()
        </div>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year PlayItOwl</p>
        </footer>
    </div>

    <script src="~/wwwroot/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/wwwroot/bower/jquery.scrollTo/jquery.scrollTo.min.js"></script>
    <script src="~/wwwroot/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/wwwroot/lib/respond/dest/respond.min.js"></script>
    <script src="~/wwwroot/lib/string/dist/string.min.js"></script>
    <script src="~/wwwroot/lib/lodash/lodash.js"></script>
    <script src="~/wwwroot/lib/bluebird/js/browser/bluebird.min.js"></script>
    <script src="//connect.facebook.net/en_US/sdk.js" id="facebook-jssdk"></script>


    <iframe id="ifDownload" style="display: none;"></iframe>
    <script src="~/wwwroot/js/Sidebar.js" type="text/javascript"></script>
    <script src="~/wwwroot/js/site.js" type="text/javascript"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

Playitowl/Views/Shared/_SearchNavBar.cshtml
@using Playitowl.Models
@model Playitowl.Models.Vm.PlaylistSearchBm

@using (Html.BeginForm("Search", "Playlist", FormMethod.Post, new
{
    @class = "navbar-form",
    id = "playlist-search-form",
    name = "search-form",
    role = "search"
}))
{
    <div class="input-group">
        @Html.TextBoxFor(x => x.SearchTerm, new
       {
           @class = "form-control",
           id = "query",
           name = "query",
           placeholder = "Name or artist"
       })
        <div class="input-group-btn">
            <button class="btn btn-success" type="submit">
                <span class="glyphicon glyphicon-search"></span>
            </button>
        </div>
    </div>
}

Playitowl/Views/Shared/_navbar.cshtml
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button> 
            @Html.ActionLink("PlayItOwl", "Index", "Home", null, new { @class = "navbar-brand" })
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            @Html.Action("LeftMenu", "Account")
            
            @Html.Action("RightMenu", "Account")
        </div><!--/.nav-collapse -->
    </div><!--/.container-fluid -->
</nav>

 